### ISSUE TITLE
Allocation profiling with incorrect stack trace?

### ISSUE THREAD

**Issue by lic9** [jvm-profiling-tools/async-profiler#437]
Hi there, we use async profiler for allocation profiling, and recently we found following stacktrace:

com/facebook/warmstorage/$internal/org/jboss/netty/channel/socket/nio/AbstractNioSelector.run
com/facebook/warmstorage/$internal/org/jboss/netty/channel/socket/nio/AbstractNioWorker.process
com/facebook/warmstorage/$internal/org/jboss/netty/channel/socket/nio/NioWorker.read
java/nio/Buffer.flip
byte[]_[k]

which seems incorrect since Buffer.flip does not do any allocation: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/nio/Buffer.java#L356

Our application is running Java 8 and we have added -XX:+DebugNonSafepoints.
Does anyone knows why this happened and if there's any workaround or fix? Thanks!

**Comment by apangin** [comment]
Please tell
 - the version of async-profiler;
 - the profiler command line;
 - the exact JVM version;
 - OS / platform info.

Is there any profiler-related warning in the JVM logs?
In particular, is there `Install JVM debug symbols to improve profile accuracy` message?

**Comment by lic9** [comment]
Thanks @apangin !

**async-profiler version**
jattach 2.0-ap built on Mar 14 2021

**command**
something like
"jattach pid load libasyncProfiler.so true start,event=alloc,file=tmp_file,threads,interval=10000000,collapsed"

**JVM version**
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM LIBGRAAL 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)

we use graal as JIT compiler

**OS**
CentOS 7.9.2009, Linux 5.6.13


Also, we dont see `Install JVM debug symbols to improve profile accuracy ` message

**Comment by apangin** [comment]
Ah, that's GraalVM.
I ran allocation profiling with GraalVM 19.3.1, and indeed saw some invalid stack traces. There is no such problem with `-XX:-UseJVMCICompiler`, so this might be Graal JIT incorrectly mapping generated machine code to Java methods.

I tried up-to-date GraalVM, and didn't see the problem either. Look like the bug has been already fixed.

**Comment by lic9** [comment]
Interesting. We'll try latest GraalVM as well and see if it is resolved. Thanks again @apangin !

**Comment by lic9** [comment]
I tried 21.1.0 GraalVM Java 8, and the problem is still there. Did you try up-to-date GraalVM Java 8 or Java 11?

**Comment by apangin** [comment]
um.. You are right. I ran more tests again, and some stack traces indeed looked invalid.

This is a GraalVM bug - I was able to reproduce it even without async-profiler.
Reported the issue against oracle/graal project: https://github.com/oracle/graal/issues/3495

**Comment by apangin** [comment]
I'll close the issue, as there is nothing to do from async-profiler side.
