### ISSUE TITLE
Profiling with cpu event not work, results are all flat

### ISSUE THREAD

**Issue by liuzhiguo630** [jvm-profiling-tools/async-profiler#444]
I first report this problem in this discussion: https://github.com/jvm-profiling-tools/async-profiler/discussions/409

# What actually happens
When I profiling with cpu event, I got this:
<img width="1217" alt="截屏2021-06-18 17 17 43" src="https://user-images.githubusercontent.com/9815635/122538423-19e46f80-d059-11eb-8bce-6d94364b9c95.png">

But this only happened in environment UAT and PRO, FAT is fine: 
<img width="1215" alt="截屏2021-06-18 17 19 32" src="https://user-images.githubusercontent.com/9815635/122538656-5b751a80-d059-11eb-9045-1b60d0c330c6.png">

# Environment
background: I used [Arthas](https://github.com/alibaba/arthas) to start async-profiler. My software is simple spring boot application, it's builded as a docker image and running in Kubernetes.

* **async-profiler**: 1.8.3
* **JDK Version**: LibericaJDK 64-Bit Server VM (25.212-b12) for linux-amd64 JRE (1.8.0_212-BellSoft-b12), built on Apr 18 2019 18:06:04 by "bellsoft" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
* **Linux Version**: 
  *  **FAT**: ~~Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019~~
  * **UAT**: ~~Linux version 3.10.0-1160.15.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623(Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Feb 3 15:06:38 UTC 2021~~
* **CPU Info**:
  * **FAT**: [cpuinfo.txt](https://github.com/jvm-profiling-tools/async-profiler/files/6684338/cpuinfo.txt)
  * **UAT**: [cpuinfo.txt](https://github.com/jvm-profiling-tools/async-profiler/files/6684341/cpuinfo.txt)
* **sysctl -a**:
  * **FAT**: [sysctl.a.txt](https://github.com/jvm-profiling-tools/async-profiler/files/6684345/sysctl.a.txt)
  * **UAT**: [sysctl.a.txt](https://github.com/jvm-profiling-tools/async-profiler/files/6684347/sysctl.a.txt)
* **ulimit -a**:
  * **FAT**: 
  * > core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 760853
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

  * **UAT**: 
  * > core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 506865
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

I notice cpuinfo are different:
FAT: 
> fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc **aperfmperf** eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 ida arat avx512_vnni

UAT: 
> fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni

FAT has **aperfmperf** but UAT haven't,  I don't know if it will affect the result.

**Comment by apangin** [comment]
1. System information looks confusing. On one hand, you write that FAT is Linux version 3.10.0-957.21.3.el7.x86_64, and UAT is Linux version 3.10.0-1160.15.2.el7.x86_64. But `sysctl` says that `kernel.osrelease = 3.10.0-1160.15.2.el7.x86_64` for FAT, and `kernel.osrelease = 3.10.0-1062.9.1.el7.x86_64` for UAT. I don't know what to believe.
I tested both 3.10.0-1062 and 3.10.0-1160, and saw no issues.
2. async-profiler 1.8.3 is outdated; current version of the profiler is 2.0. For the community support, please check the latest version. Additionally, version 2.0 is more verbose in reporting warnings/errors. Please include all warning/error messages from the profiler, if there are any.
3. Are there normal stack traces in other profiling modes: `alloc` and `lock`?

**Comment by liuzhiguo630** [comment]
> 1. System information looks confusing. On one hand, you write that FAT is Linux version 3.10.0-957.21.3.el7.x86_64, and UAT is Linux version 3.10.0-1160.15.2.el7.x86_64. But `sysctl` says that `kernel.osrelease = 3.10.0-1160.15.2.el7.x86_64` for FAT, and `kernel.osrelease = 3.10.0-1062.9.1.el7.x86_64` for UAT. I don't know what to believe.
>    I tested both 3.10.0-1062 and 3.10.0-1160, and saw no issues.
> 2. async-profiler 1.8.3 is outdated; current version of the profiler is 2.0. For the community support, please check the latest version. Additionally, version 2.0 is more verbose in reporting warnings/errors. Please include all warning/error messages from the profiler, if there are any.
> 3. Are there normal stack traces in other profiling modes: `alloc` and `lock`?

1. We tried upgrade linux version afterwards, sorry about mistakes. Correct's here:
**Linux Version(/proc/version)**:
**FAT**: Linux version 3.10.0-1160.15.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623(Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Feb 3 15:06:38 UTC 2021
**UAT**: Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019
2. OK I'll try it later.
3. I just confirmed alloc and lock are fine. BTW, we use alloc positioned GC problem recently, it is really cool.

**Comment by liuzhiguo630** [comment]
> 2. async-profiler 1.8.3 is outdated; current version of the profiler is 2.0. For the community support, please check the latest version. Additionally, version 2.0 is more verbose in reporting warnings/errors. Please include all warning/error messages from the profiler, if there are any.

I tried async-profiler 2.0, still not work:
<img width="2092" alt="截屏2021-06-22 11 43 47" src="https://user-images.githubusercontent.com/9815635/122859774-1c8fdf00-d34f-11eb-801c-f373faed4481.png">

And I did't see any warning or tips, is there some logs in async-profiler?

**Comment by apangin** [comment]
I was not able to reproduce the problem, even with the same software versions as you mention.

This looks as if the operating system does not set the context stack pointer properly when calling a signal handler. In order to verify the hypothesis, I created the special version of the profiler that records additional debug info in .jfr format.

I pushed it to [flat-stacks](https://github.com/jvm-profiling-tools/async-profiler/commits/flat-stacks) branch.  
And here is the prebuilt binary: [async-profiler-2.0-ctx-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/6705100/async-profiler-2.0-ctx-linux-x64.tar.gz)

Could you run in on the system where Java stacks are not collected and share the generated .jfr file? This doesn't need to be a production application - just any "hello world"-like program that runs long enough to collect a meaningful profile.
The command line to record .jfr:
```
./profiler.sh -d 10 -e itimer -f out.jfr <pid>
```

If you prefer not to share the output here, you may email me `out.jfr` privately to < upload at pangin.pro >

**Comment by liuzhiguo630** [comment]
[uat-monitor.out.jfr.zip](https://github.com/jvm-profiling-tools/async-profiler/files/6706042/uat-monitor.out.jfr.zip)

**Comment by liuzhiguo630** [comment]
Thanks for your interest, I hope I didn't waste your time. I've checked the output, there are no sensitive information.

**Comment by liuzhiguo630** [comment]
update: I tried make Uat's host machine spec and Kubernetes version same with Fat. And checked `/proc/version` and `/proc/cpuinfo`, they are exactly same. But still not work.

**Comment by apangin** [comment]
Thanks for the jfr - it helps.
The problem turned out to be so ridiculous! :)
There is `-XX:MaxJavaStackTraceDepth=-1` option among your Java flags - it prevents JVM from building async stack traces. Just remove this option, or set it to a deliberately large value like `-XX:MaxJavaStackTraceDepth=100000`

**Comment by liuzhiguo630** [comment]
HOLY SHIIIT !!-_-
It's totally my bad, I should read **Restrictions/Limitations** part very seriously at the beginning. 
This case remind me, if things become complex and unreasonable, must have some simple thing that we missed.

Thank you again, I have to say your project greatly improve the observability of Java. Wish you all the best.
